### ISSUE TITLE
error: no json object could be decoded

### ISSUE THREAD

**Issue by mhogomchungu** [jas-per/luckyLUKS#4] opened 2015-03-10 13:54 UTC
trying to unlock a volume fails here with a dialog box that reads:

```
error in communication:
No JSON object could be decoded.
```

how can i work around that error?

clicking ok and the application disappears but the process viewer shows python process and sudo process started by luckyLUKS are still running.

while here,i should ask.

How did you set up sudo in your system to take user password? your application seem to just hang before before the GUI shows up if sudo asks for user password on the terminal.I had to setup sudo to not require password at all(passwordless sudo) to make your tool start.

**Comment by jas-per** [comment] 2015-03-11 21:10
Thanks checking out luckyLUKS and especially for your the work on ZuluCrypt - been an long time user and happy to be able to deal with all my encrypted container stuff with the gui it provides. I see both tools as complementary with ZuluCrypt providing all possible options to encrypted containers and luckyLUKS providing a simplified user interface for starters and casual computer users.

To reproduce your bug it would be great if you could supply more details about your setup: distribution, desktop environment, python & kernel version. Looks like a problem with the IPC between the app and sudo - is there any error output when started from the command line?

**Comment by mhogomchungu** [comment] 2015-03-11 22:01
desktop: kde 4.14.3
distribution: pclinuxos
python version: 2.7.6
kernel: 3.15.9-pclos1

a bit of testing and i think i know where the problem is.I did my test on an old volume of mine that has a size that is not a multiple of 512 and losetup produces the following warning when attaching a loop device to it:

```
[root@ink mtz]# losetup /dev/loop0 eee.bin 
losetup: eee.bin: warning: file does not fit into a 512-byte sector the end of the file will be ignored.
[root@ink mtz]# 
```

Create an image file with a size that is not a multiple of 512 and you should get the problem.

I think your tool gets confused by losetup output because it doesnt expect it.

Why do you set up loop devices yourself? cryptsetup will do it for you when its given an image file.

**Comment by jas-per** [comment] 2015-03-12 17:22
I was able to reproduce the sudo issue you found and the losetup one too - will fix asap. I set up the loopback devices myself to workaround a bug with udisks-daemon: Closing an encrypted container with cryptsetup handling the loopback device will almost always crash the daemon because the events get messed up (udisks1, udisksd from udisks2 is fine)

**Closed as completed** 2015-03-13 18:41 UTC
